version: '3.8'

services:
  vue-app:
    image: node:18-alpine
    container_name: vue-frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run dev -- --host"
